"""add_macro_data_fixed

Revision ID: 0d1860d818e6
Revises: d4db413ede26
Create Date: 2026-01-20 04:19:59.681030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1860d818e6'
down_revision: Union[str, Sequence[str], None] = 'd4db413ede26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('indicator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'indicator', name='_macro_date_indicator_uc')
    )
    op.create_index('ix_macro_date', 'macro_data', ['date'], unique=False)
    op.create_index('ix_macro_indicator', 'macro_data', ['indicator'], unique=False)
    op.create_index('ix_macro_indicator_date', 'macro_data', ['indicator', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_macro_indicator_date', table_name='macro_data')
    op.drop_index('ix_macro_indicator', table_name='macro_data')
    op.drop_index('ix_macro_date', table_name='macro_data')
    op.drop_table('macro_data')
    # ### end Alembic commands ###
