"""add_decision_logs_table

Revision ID: 1deec0976e76
Revises: 01225e17789b
Create Date: 2026-01-25 19:24:35.025188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1deec0976e76'
down_revision: Union[str, Sequence[str], None] = '01225e17789b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('decision_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(length=1000), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('risk_status', sa.String(length=20), nullable=True),
    sa.Column('key_risks', sa.JSON(), nullable=True),
    sa.Column('current_weights', sa.JSON(), nullable=True),
    sa.Column('proposed_weights', sa.JSON(), nullable=True),
    sa.Column('max_drift', sa.Float(), nullable=True),
    sa.Column('macro_regime', sa.String(length=20), nullable=True),
    sa.Column('vix_level', sa.Float(), nullable=True),
    sa.Column('trade_required', sa.Boolean(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('execution_timestamp', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('user_query', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_logs_portfolio_id'), 'decision_logs', ['portfolio_id'], unique=False)
    op.create_index('ix_decision_portfolio', 'decision_logs', ['portfolio_id'], unique=False)
    op.create_index('ix_decision_timestamp', 'decision_logs', ['timestamp'], unique=False)
    op.create_index('ix_decision_type', 'decision_logs', ['decision_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decision_type', table_name='decision_logs')
    op.drop_index('ix_decision_timestamp', table_name='decision_logs')
    op.drop_index('ix_decision_portfolio', table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_portfolio_id'), table_name='decision_logs')
    op.drop_table('decision_logs')
    # ### end Alembic commands ###
