"""Created news Tables: pipeline_runs, api_quotas, api_call_logs

Revision ID: 21f92620c49c
Revises: a994ff3c87ed
Create Date: 2025-11-11 15:30:21.362200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f92620c49c'
down_revision: Union[str, Sequence[str], None] = 'a994ff3c87ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('bucket_key', sa.String(length=255), nullable=False),
    sa.Column('calls_consumed', sa.Integer(), nullable=False),
    sa.Column('window_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_quotas_bucket_key'), 'api_quotas', ['bucket_key'], unique=True)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='pipelinerunstatus'), nullable=False),
    sa.Column('git_commit_hash', sa.String(length=40), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_script_name'), 'pipeline_runs', ['script_name'], unique=False)
    op.create_table('api_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('endpoint_name', sa.String(length=255), nullable=True),
    sa.Column('asset_ticker', sa.String(length=20), nullable=True),
    sa.Column('call_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_call_logs_asset_ticker'), 'api_call_logs', ['asset_ticker'], unique=False)
    op.create_index(op.f('ix_api_call_logs_pipeline_run_id'), 'api_call_logs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_api_call_logs_provider_name'), 'api_call_logs', ['provider_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_call_logs_provider_name'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_pipeline_run_id'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_asset_ticker'), table_name='api_call_logs')
    op.drop_table('api_call_logs')
    op.drop_index(op.f('ix_pipeline_runs_script_name'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_api_quotas_bucket_key'), table_name='api_quotas')
    op.drop_table('api_quotas')
    # ### end Alembic commands ###
