"""FinancialStatement Tabelle hinzugefügt. Nach dem Schema: Fixed FS Data und rest JSON Dump

Revision ID: 67cc3e174858
Revises: 21f92620c49c
Create Date: 2025-11-21 00:54:56.233875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67cc3e174858'
down_revision: Union[str, Sequence[str], None] = '21f92620c49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', 'report_type', 'period_type', name='_asset_financial_statement_uc')
    )
    op.create_index(op.f('ix_financial_statements_asset_id'), 'financial_statements', ['asset_id'], unique=False)
    op.create_index(op.f('ix_financial_statements_date'), 'financial_statements', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_statements_date'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_asset_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    # ### end Alembic commands ###
