"""Created news Tables: pipeline_runs, api_quotas, api_call_logs

Revision ID: a994ff3c87ed
Revises: c1e79ae31788
Create Date: 2025-11-11 15:29:09.263116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a994ff3c87ed'
down_revision: Union[str, Sequence[str], None] = 'c1e79ae31788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
