"""add_financial_statement_raw_data

Revision ID: b2663cf9d397
Revises: 67cc3e174858
Create Date: 2025-11-21 17:43:36.198656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2663cf9d397'
down_revision: Union[str, Sequence[str], None] = '67cc3e174858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_statements', sa.Column('cost_of_revenue', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('research_and_development', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('selling_general_and_administrative', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('interest_expense', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('income_tax_expense', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('accounts_receivable', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('inventory', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('property_plant_equipment', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('accounts_payable', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('current_debt', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('long_term_debt', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('common_stock', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('retained_earnings', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('accumulated_other_comprehensive_income', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('depreciation_and_amortization', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('stock_based_compensation', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('change_in_working_capital', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('capital_expenditure', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('dividends_paid', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('issuance_of_debt', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('repayment_of_debt', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('issuance_of_stock', sa.Float(), nullable=True))
    op.add_column('financial_statements', sa.Column('repurchase_of_stock', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_statements', 'repurchase_of_stock')
    op.drop_column('financial_statements', 'issuance_of_stock')
    op.drop_column('financial_statements', 'repayment_of_debt')
    op.drop_column('financial_statements', 'issuance_of_debt')
    op.drop_column('financial_statements', 'dividends_paid')
    op.drop_column('financial_statements', 'capital_expenditure')
    op.drop_column('financial_statements', 'change_in_working_capital')
    op.drop_column('financial_statements', 'stock_based_compensation')
    op.drop_column('financial_statements', 'depreciation_and_amortization')
    op.drop_column('financial_statements', 'accumulated_other_comprehensive_income')
    op.drop_column('financial_statements', 'retained_earnings')
    op.drop_column('financial_statements', 'common_stock')
    op.drop_column('financial_statements', 'long_term_debt')
    op.drop_column('financial_statements', 'current_debt')
    op.drop_column('financial_statements', 'accounts_payable')
    op.drop_column('financial_statements', 'property_plant_equipment')
    op.drop_column('financial_statements', 'inventory')
    op.drop_column('financial_statements', 'accounts_receivable')
    op.drop_column('financial_statements', 'cash_and_cash_equivalents')
    op.drop_column('financial_statements', 'income_tax_expense')
    op.drop_column('financial_statements', 'interest_expense')
    op.drop_column('financial_statements', 'selling_general_and_administrative')
    op.drop_column('financial_statements', 'research_and_development')
    op.drop_column('financial_statements', 'cost_of_revenue')
    # ### end Alembic commands ###
