"""add operating_cash_flow to financialstatements table

Revision ID: d4db413ede26
Revises: b2663cf9d397
Create Date: 2025-11-21 18:01:11.712942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4db413ede26'
down_revision: Union[str, Sequence[str], None] = 'b2663cf9d397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_statements', sa.Column('operating_cash_flow', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_statements', 'operating_cash_flow')
    # ### end Alembic commands ###
